### ISSUE TITLE
Make production more efficient

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/ra-manual#1]
Jesse and I [Matt] wanted to have a quick debrief about the [TRANS production](https://asjira.stanford.edu/jira/browse/TRANS-451) process to see if there's anything we can tweak to make the [process](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production) more efficient going forward. Overall, we were extremely happy with the work you all did.

Two small things I thought of:

(1) In PROOF, I would like the RAs to go ahead an correct any clear typos or other errors that you are ~100% sure we would want to correct, and for which there is no uncertainty about how they should be corrected. This would include things like "...Texas and and Massachusetts," misspellings, etc.

(2) In a couple of cases you were producing "big" deliverables containing all the output from a task and then a subset flagged for our attention. From our perspective, it's only the attention part that matters, and we want to make sure you're not spending extra time making the big deliverables pretty. You should view the deliverable of the tasks as the handoff to us of info we need to see; how everything is organized on the backend is up to you and should be as efficient as possible.

Let us know if you agree with these points and whether there are any other changes you guys see that would make the process more efficient.

**Comment by arosenbe** [comment]
@lboxell, @M-R-Sullivan, and @stanfordquan 

We should find some time to discuss the above, either today or early next week.

@yuchuan2016, I tagged you in this discussion, even though you weren't working on the production in question. We're happy to hear any thoughts you have on how to make production more efficient. You can also take yourself off the task if you don't have any. Either way's fine.

**Comment by lboxell** [comment]
One thought I had is whether we want to use the pull request functionality on GitHub to replace PDF deliverables for some tasks. E.g., for REF, you create a branch and implement your changes. You then create a pull request and flag any ATN items with a review for MG/JMS to look at. 

I'm not sure how this would look for PROOF, so perhaps it will only work for some tasks.

**Comment by arosenbe** [comment]
@gentzkow and @jmshapir, 

Notifying you of this thread. We'll ping you again after we've had some time to discuss.

**Comment by M-R-Sullivan** [comment]
Initial comments:
- I think that we will need to rewrite the EXT section for the post-SVN age
- I would like if the MATH description was clearer about the extent of the checks we should make in this task. [The description](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production#task-math-check-theoretical-claims-in-the-paper) suggests that we should just look through the main text and flag all claims that are not either trivial, supported by proofs, or otherwise supported. But in the last TRANS production we looked over some of the proofs, too, and this seems to have been fruitful.

**Comment by stanfordquan** [comment]
Quick comments before discussing more.

The editing tasks (`PROOF`, `MATH`, `FACT`, `REF`) as listed are not consistent with practice. This is what I actually have been doing for the last three rounds (maybe that means I should start sticking to the script).
	- I send two deliverables, a `for attention` version marked `ATTN`, and the full file with both `for attention` fixes and obvious fixes. (current deliverable says one file)
	- While I wait for Matt/Jesse look at the `ATTN` version, I fix the obvious errors. (current manual says RAs sit tight until Matt/Jesse get back) (this saves calendar time by quite a bit)
	- Matt/Jesse return with marked up `ATTN` files, some with action items and some without. I carry out the action items, edit the draft, so on. (*)
	- For [PROOF] or whatever the last outstanding production task is, after all edits are made, I or another RA proofread the draft one more time before closing the task. (probably common-sense but not in the manual)

The last step is important. Without it, work carried out in (*) is without peer-review. That is necessary given comments like Jesse's in the last PROOF round:

>Let's be sure we haven't introduced typos like this in other areas where we're making edits, since we don't have another line of defense after this proofreading. 

or an incidence a month back where I accidentally deleted a line after merging the PROOF branch into `master` after change in paragraph order in the `master` branch. This went un-noticed even after the last step. 

I think now that we're in git-land, pull requests will help minimize errors. Nonetheless, the final `merge` commit warrants peer review.

**Comment by lboxell** [comment]
We agree with MG's points (1) and (2) from https://github.com/gslab-econ/ra-manual/issues/1#issue-218548851. 

Other comments we thought of:
 - In git, we should have a `production` branch. Then each task that edits the code/paper should have its own sub-branch which gets merged into the `production` branch when finished. At least one RA does a final, "PR" of the pull-request for the `production` branch into `master` before releasing/submitting the `master` branch. 
 - Add a pointer to the commits that make non-ATN changes for MG/JMS if they want to skim through as a part of the deliverable. 
 - EXT should be updated. Scons will take care of most things, and then we just need to do a manual check of outside calls (SVN, Drive, Dropbox).
 - For MATH, it may be useful to have a little more clarity on what is supposed to be checked. I.e., should we go through the proofs line-by-line, or just review the non-proof mathematical claims. Perhaps this is something that will vary based on the paper?

**Comment by lboxell** [comment]
@stanfordquan @arosenbe @M-R-Sullivan, see above. If there is nothing else, I'll ping MG/JMS with the above.

**Comment by M-R-Sullivan** [comment]
@lboxell - Nothing else

**Comment by lboxell** [comment]
@gentzkow @jmshapir,

See https://github.com/gslab-econ/ra-manual/issues/1#issuecomment-292651910 for our thoughts on production.

**Comment by gentzkow** [comment]
Great. Thanks guys. I am fine signing off on all these suggestions. For MATH, I think the default instructions should be no line-by-line checking of proofs, but we can also make a note that we can revise this on a case-by-case basis. Probably a good idea if the RA launching production pings MG/JMS to confirm whether we want to modify the MATH instructions.

One other thought: Would it make sense to specify a "typical" range of person-days for each production task? Obviously it varies a lot paper to paper, but I think it could be helpful to fix expectations. This way if a task looks like it's going to take much more time than typical RAs can check with MG/JMS to make sure this is intended.

**Comment by lboxell** [comment]
Time estimates (and RA allocation) for new, full-length paper:

 - PROOF -- 64 hours (4 RAs, 2 days)
    - Social-text took 63 hours
 - REF -- 8 hours (1 RA, 1 day)
   - Social-text took 20 hours???
 - FACT -- 12 hours (2 RAs, 3/4 day)
 - REPLY -- 16 hours (2 RAs, 1 day)
 - MATH -- 16 hours (2 RAs, 1 day) [Assuming proofs are not checked]
 - PRELIM -- 4 hours (1 RA, 1/2 day)
 - EXT -- 12 hours (1 RA, 1.5 days) [Maybe less in a scons framework]
 - DEF -- 8 hours (1 RA, 1 day)
 - SOURCE -- 4 hours (1 RA, 1/2 day)
 - THANKS -- 4 hours (1 RA, 1/2 day)
 - PLOT -- 8 hours (1 RA, 1 day) [if plots need to be changed]

Total: 156 hours (roughly 1 week for 4 RAs)


@arosenbe @M-R-Sullivan  @stanfordquan, Thoughts on the above?

**Comment by lboxell** [comment]
@gentzkow,

The time estimate idea sounds good. The above comment gives an estimate by task. Let me know if you have any thoughts on it. If not, I'll also add these estimates to the RA manual.

**Comment by gentzkow** [comment]
Thanks all. I think the idea of including estimates like this is very good. My main question now is whether we're happy with allocating this much time to production.

@lboxell: To help me think about it, can you let me know where there is redundancy built in here? E.g., is the allocation for PROOF 4 RAs each doing a complete proofread of the paper? Where else do we have multiple people duplicating the same work?

@jmshapir: Let me know if you have thoughts, or if you want to discuss by phone.

**Comment by lboxell** [comment]
@gentzkow,

I think wherever you have multiple RAs, there is redundancy equal to the number of RAs.

**Comment by gentzkow** [comment]
@jmshapir: I would propose that we cut the number of RAs on PROOF from 4 to 2. Otherwise, I think the level of redundancy here makes sense. But I'd like to know your thoughts.

**Comment by jmshapir** [comment]
@gentzkow I agree with that change and I also agree that nothing else jumps out at me as an obvious thing to cut.

**Comment by lboxell** [comment]
@arosenbe, I'm sure you'll enjoy doing a quick PR on [this](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production/_compare/0541e233f5e39393744ac827bc171bb72a99ef14...4429da091290cb6f8715aa1af127534b5f3c2de1).

**Comment by lboxell** [comment]
If you see something that needs to be changed, it may be more efficient to just make the change and then I can review your change-log. (Unless you there are more substantial changes that will take a while to do.)

**Comment by arosenbe** [comment]
@lboxell, 

Looks good. Just a few changes in the diff [here](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production/_compare/4429da091290cb6f8715aa1af127534b5f3c2de1...cae517b58233930051caceeb09758082dd4b3ef6).

**Comment by lboxell** [comment]
Thanks, @arosenbe. Your changes look good. I made one small deletion [here](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production/_compare/cae517b58233930051caceeb09758082dd4b3ef6...04604c2d58bf09173f1c3644df6f8efbb49baa38) that I think you forgot.

Will close this task.

Summary:
  - Updated RA manual to include time estimates and default RA allotments. 
  - Edited some task descriptions to make them more efficient and updated for a github world.
