### ISSUE TITLE
Closing issue after pull request

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/ra-manual#2]
@gentzkow what would you think about revising our process so that once a pull request for an issue is opened the issue is closed unless there is a reason to expect further work beyond the pull?

I find we often track essentially the same issue in multiple places, e.g. 
[issue](https://github.com/TaddyLab/politext/issues/383)
[pull](https://github.com/TaddyLab/politext/pull/431)

On this model, "pull request" would essentially become our notation for "under peer review," which is probably more consistent with git style anyway.

Just a thought, not wedded to this.

**Comment by gentzkow** [comment]
That would be fine. I like getting rid of the redundancy of having to flag issues as in peer review + also have the pull request open.

I would prefer that we keep the convention of having a final comment in the original task summarizing the resolution & location of deliverable. And we might want to have an explicit comment saying "Tread continues in [pull request](...)" or something similar.

Do you want to update the RA manual and let the team know?

**Comment by jmshapir** [comment]
Great. @M-R-Sullivan see above. When you have a minute can you implement this proposed change, with @gentzkow's modifications, and then notify the gang with a tag here?

**Comment by M-R-Sullivan** [comment]
@jmshapir - I made the edits. You can see the diff [here](https://github.com/gslab-econ/ra-manual/wiki/Tasks/_compare/6f0a0e501bd5eb0042772b2c2df089bc661cabbb...6294433a18d2ab88de744922a1d42d18062092a3). 

@arosenbe, @lboxell, @stanfordquan, @yuchuan2016, @Shun-Yang, & @meeranmismail: see above.

**Comment by jmshapir** [comment]
Something weird was going on with the bullets there so I fixed it.

**Comment by arosenbe** [comment]
@jmshapir, 

Since issues will no longer overlap with pull requests, should we send a link to stale pull requests in emails as well?

Also, GitHub  changed switched to CommonMark a few weeks ago [source](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown), which messed with our formatting a bit. Thanks for cleaning it up!

**Comment by jmshapir** [comment]
@arosenbe yes I think we should include pulls as "stale," thanks.

**Comment by M-R-Sullivan** [comment]
@jmshapir - I sense that there's nothing left to be done here, so I'll close this issue now. 

**Summary**
- Established practice of closing GitHub issues once their corresponding pull requests are opened, as described in the comments [here](https://github.com/gslab-econ/ra-manual/issues/2#issue-222140443) and [here](https://github.com/gslab-econ/ra-manual/issues/2#issuecomment-294514519).
- Described this practice on [this page](https://github.com/gslab-econ/ra-manual/wiki/Tasks) of the RA manual.
