### ISSUE TITLE
Update storage protocol

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/ra-manual#4]
We have switched from Google Drive and the `gdrive` tool to Dropbox and `rclone`. The goal of this task is to update our storage page to current practice.

**Comment by arosenbe** [comment]
@lboxell, 

Can you take a look at my draft of the new storage section? 

<details>
  <summary> Click for section.</summary>

The way we set up storage is based on an important principle: Any task you work on should be either completed (all files are clean, documented, and checked into the system ready for others to use them) or abandoned (all files deleted), but never left indefinitely in a half-finished state. This will be easy if you structure your work in discrete chunks and follow the rules of organization, documentation, commenting, etc. as you go.

### Main locations

#### GitHub

GitHub is our main storage location for code and small data files.

There are two ways of storing something on GitHub: regularly within the repo and in [git-lfs](https://git-lfs.github.com/).

The following types of files are the __only__ files that can be stored regularly in the GitHub repository:
 - Diffable files (.txt, .csv, .R, .do, etc.) that are under 5 MB.

The following files can be stored in git-lfs:
 - Files that are not diffable (binaries, such as: .pdf, .dta, .rds, etc.)
 - Diffable files that are over 5 MB.

All non-diffable files should be added to the git-lfs tracking (e.g., `git lfs track *.pdf`). This will cause git to automatically place these files within git-lfs. Large diffable files should be added to lfs manually (e.g., `git lfs track output/data/somebigfile.txt`). 

The total size of the files within the regular GitHub storage should not exceed 1 GB per repository (including version history). The total size of a repository, including all files in LFS and their version history, should not exceed 5 GB. If a repository uses input or produces output that is larger than this, the large input or output files should be stored separately.

 
#### Dropbox

We use Dropbox to store large raw and intermediate data files and [`rclone`](https://rclone.org/) to access them. Raw data files should be changed infrequently, if ever. 

##### Basic structure

We use the `gslab_data` directory as our primary storage location. Two subdirectories, `raw` and `intermediate` are used for raw and intermediate files. New subdirectories added to `raw` should have the following structure

```
raw-data
├── new subdirectory
│   ├── data 
│   ├── orig 
|   └── readme
└── stable subdirectory
```

We also use a `Temporary file share` to pass large temporary files and directories between one another when nececssary. Nothing in this directory should be considered stable by default.

##### Permission control

*  The default permission for the `gslab_data`, `raw`, and `intermediate` directories is *can edit* so that all shared members can add new subdirectories in this folder.
*  Set stable subdirectories to *can view*.
*  To edit a stable directory, an administrator (MG, JMS, or an RA with admin responsibilities)  will need to change the permission of that directory from **can view** to **can edit**. Note that all subdirectories of that directory will inherit such change.   

##### Storage and versions 

We have theoretically unlimited potential storage on Dropbox, but our capacity at any point in time is limited. Before adding new assets, check that they will not exceed the cap. If they will exceed the cap—or if we seem to be running low on storage space—contact MG.    

Dropbox supports unlimited version history for all files, unless the history is explicitly deleted. We should always use the most up-to-date version of each file. If there is an error with the most recent version, it should be fixed (possibly using the version history). 
</details>

**Comment by lboxell** [comment]
@arosenbe, Looks good. Maybe add a note about the difference between 'orig' and 'data' and that the former is only necessary if changes (typically only formatting changes) have been made from the originally received data.

Also, do you need admin privileges to Dropbox as SuperRA?

**Comment by arosenbe** [comment]
@lboxell 

I added this paragraph after the diagram

When we produce or receive data, we store it as-is in the `orig` directory and perform no direct edits. Scripts to clean the data in `orig` are stored in `code`; they should be especially light and easy to understand. The output from the cleaning scripts is stored in `data` for use as an input in further analysis or formatting. If no cleaning is necessary, the `code` and `data` directories should not be created. The readme should be a markdown or text file that briefly describes the contents of `orig` and how it was acquired, the outputs stored in `data`, and the cleaning steps taken in `code`. Detailed information not suitable for a readmen can be provided in a `docs` subdirectory.   

-------------

I do need admin privileges to Dropbox.

**Comment by lboxell** [comment]
@arosenbe, Looks good. Added admin privileges to dropbox.

**Comment by arosenbe** [comment]
Summary 

Change the Google Drive discussion in Storage to Dropbox. View the diff [here](https://github.com/gslab-econ/ra-manual/wiki/Storage/_compare/21db81b296c54e7b595e91608e908f733c2cd2c4...36078515b4cdd298379d254ec2ecad9ce85f4258) and the new page [here](https://github.com/gslab-econ/ra-manual/wiki/Storage/36078515b4cdd298379d254ec2ecad9ce85f4258).
